#!/bin/bash

NAME=robotica
DIR=/home/robotica/WeedYardDoc/backend
USER=robotica
GROUP=robotica
WORKERS=3
BIND=unix:/home/robotica/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=backend.settings
DJANGO_WSGI_MODULE=backend.wsgi
LOG_LEVEL=error

cd $DIR

. ../../bin/activate

export DJANGO_SETTING_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
	--name $NAME \
			--workers $WORKERS \
			--user=$USER \
			--group=$GROUP \
			--bind=$BIND \
			--log-level=$LOG_LEVEL \
			--log-file=-
